include ':app'
include ":adaptation_aux_virus"
include ":auto_hypnose"
include ":bain_d_hypnose"
include ":bien_dormir"
include ":calmer_l_anxiete"
include ":confiance_en_soi"
include ":createur_de_realite"
include ":curatif"
include ":estime_de_soi"
include ":expansion"
include ":gerer_le_stress"
include ":histoire_de_la_vie"
include ":immersion_sensorielle"
include ":intuition"
include ":la_conscience"
include ":l_inconscient"
include ":magie_interieur"
include ":preventif"
include ":ressourcement"
include ":retrouver_le_moral"
include ":reussir_sa_vie"
include ":s_endormir"
include ":soigner_son_passe"
include ":transformer_vos_peurs"

