#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Nov 30 22:43:35 CET 2018
apiSecret=29f8eb1ad6cf22a06f4761fc0565f3652eb186ad4f960706e65baccd39625f70
