plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.playassetdelivery'
version = '0.1.0'

android {
  namespace "expo.modules.playassetdelivery"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.play:asset-delivery:2.3.0'
  implementation 'com.google.android.play:asset-delivery-ktx:2.3.0'
}
