import type { Sample } from "@/typings/recording";

export const SAMPLES: Sample[] = [
  {
    id: "efb3b76e-94d8-4a41-b3bf-7a39f81eea98",
    rid: "bien-dormir",
    title: "Bien dormir",
    label: "Bien dormir",
    description: `Voici un texte composé par Patricia d'Angeli, puis enregistré également par elle (l'ambiance musicale est d'Olivier Lockert). Comme son titre l'indique, cet enregistrement est destiné à vous accompagner durant votre endormissement, soit pour vous aider à vous endormir, soit pour faire en sorte que votre nuit se passe bien. Vous avez juste à poser les écouteurs ou le casque de votre smartphone sur vos oreilles, et laisser faire. Pas besoin d'écouter vraiment ou de chercher à comprendre, juste vous laisser bercer. L'accompagnement musical est minimal et, comme la voix, s'en ira progressivement afin de ne pas troubler votre sommeil.`,
    duration: 19,
    pack: { name: "bien_dormir", file: "bien-dormir.mp3" },
  },
  {
    id: "69f1efb0-9dcd-41cb-8120-682d59b6b122",
    rid: "s-endormir",
    title: "S'endormir",
    label: "S'endormir en auto-hypnose",
    description: `Le premier protocole du livre "Auto-hypnose pour débutants" : comment trouver le sommeil. Ecoutez au casque, afin de profiter au mieux de l'accompagnement musical. Pour cette séance, une induction hypnotique a été utilisée parmi celles présentées dans le livre. Bien sûr, lorsque vous pratiquez de manière autonome, vous pouvez utiliser votre méthode préférée. De même, lorsque vous pratiquez en solo, vous n’avez pas besoin de parler ou de mentaliser les paroles. Il suffit de penser à ce que vous voulez, comme une intention. Avec la pratique, tout s’automatise et seule votre intention dirige la séance.`,
    duration: 30,
    pack: { name: "s_endormir", file: "s-endormir.mp3" },
  },
  {
    id: "fba20c88-66f9-475a-96b4-43722c85fe0b",
    rid: "preventif",
    title: "Préventif",
    label: "Système immunitaire préventif",
    description: `Cette induction a été conçue, à l'origine, pour aider lors de l'épidémie de grippe H1N1 de l'hiver 2009. Cet enregistrement est à écouter avant l'enregistrement "Curatif" afin de bien comprendre l'esprit dans lequel vous mettre. Le texte est explicatif, avec de nombreuses métaphores. Le tout est dit assez rapidement, de manière à exciter, stimuler, vos processus psychophysiologiques. Texte et musique d'Olivier Lockert.`,
    duration: 27,
    pack: { name: "preventif", file: "preventif.mp3" },
  },
  {
    id: "27c5da5f-e3a8-4743-8627-cb8065dd80e7",
    rid: "curatif",
    title: "Curatif",
    label: "Système immunitaire curatif",
    description: `Cet accompagnement est curatif. C'est-à-dire que vous n'en avez besoin que si vous êtes malade. Le texte est dit lentement et la musique est hypnotique. Même si beaucoup de choses sont encore expliquées, le texte n'est pas pour votre esprit conscient, fermez les yeux et passez un bon moment, sans chercher à comprendre, ni même à écouter. S'il vous arrive de ne plus entendre, comme si vous pensiez à autre chose ou comme si vous aviez dormi : c'est parfait !`,
    duration: 36,
    pack: { name: "curatif", file: "curatif.mp3" },
  },
  {
    id: "a439d9f2-eac8-4ec6-8256-c2b003143869",
    rid: "renforcement",
    title: "Renforcement",
    label: "Renforcer son système immunitaire",
    description: `Voici un exercice sur le thème "Stimulez votre système immunitaire". Il s'agit ici de libérer un éventuel blocage émotionnel, dans les cas où tout semble correct au niveau du corps, et pourtant, vous n'allez pas mieux. Vous pouvez aussi écouter cette séance à titre préventif, avec l'idée suivante en tête : "Cher Inconscient, si quelque chose devait me stresser ou me bloquer, de là à fragiliser mon immunité, dis-le moi avant ou fais ce qu'il faut pour que tout se passe bien". Texte et voix d'Olivier Lockert.`,
    duration: 21,
    pack: { name: "renforcement", file: "renforcement.mp3" },
  },
  {
    id: "eddfd60e-b48f-47c0-bf01-ae40f4daa275",
    rid: "ressourcement",
    title: "Ressourcement",
    label: "Bulle de ressourcement thérapeutique",
    description: `L'idée est de se reconnecter aux forces vitales, puis de plonger dans un espace de ressourcement, afin de renforcer et d'accélérer la guérison du corps. Le fond sonore est lancinant, onirique, afin de vous bercer. Rien à faire, rien à penser, juste vous laisser faire. Allongez-vous ou installez-vous confortablement, et laissez aller. Dans les situations les plus difficiles, utilisez cette induction au moins une fois par jour. Vous pouvez vous endormir pendant l'accompagnement, car l'action consciente, volontaire, est inutile.`,
    duration: 30,
    pack: { name: "ressourcement", file: "ressourcement.mp3" },
  },
  {
    id: "dd0e3dee-3330-4383-b221-e829d2c20025",
    rid: "adaptation-aux-virus",
    title: "Adaptation aux virus",
    label: "Adaptation aux virus",
    description: ``,
    duration: 24,
    pack: { name: "adaptation_aux_virus", file: "adaptation-aux-virus.mp3" },
  },
  {
    id: "9bb5e6c5-e4b5-417d-93e3-f3f12dbfb333",
    rid: "retrouver-le-moral",
    title: "Retrouver le moral",
    label: "Retrouver le moral",
    description: ``,
    duration: 16,
    pack: { name: "retrouver_le_moral", file: "retrouver-le-moral.mp3" },
  },
  {
    id: "a0683c11-4dc5-414a-9643-9df6e9e9c5b0",
    rid: "joie-de-vivre",
    title: "Joie de vivre",
    label: "Retrouver sa joie de vivre",
    description: ``,
    duration: 23,
    pack: { name: "joie_de_vivre", file: "joie-de-vivre.mp3" },
  },
  {
    id: "d28062c7-0655-442c-8c54-0e3cff8b0350",
    rid: "confiance-en-soi",
    title: "Confiance en soi",
    label: "Confiance en soi",
    description: ``,
    duration: 39,
    pack: { name: "confiance_en_soi", file: "confiance-en-soi.mp3" },
  },
  {
    id: "032e9cd5-d18d-4b7b-9961-4a54b610918a",
    rid: "estime-de-soi",
    title: "Estime de soi",
    label: "Estime de soi",
    description: ``,
    duration: 25,
    pack: { name: "estime_de_soi", file: "estime-de-soi.mp3" },
  },
  {
    id: "872ee262-935b-4035-83d6-6bcb9cccd533",
    rid: "retrouver-sa-confiance",
    title: "Retrouver sa confiance",
    label: "Retrouver sa confiance en soi",
    description: ``,
    duration: 29,
    pack: { name: "retrouver_sa_confiance", file: "retrouver-sa-confiance.mp3" },
  },
  {
    id: "4ce56de7-1723-47ab-b4b4-ea1cf60d3cc8",
    rid: "calmer-l-anxiete",
    title: "Calmer l'anxiété",
    label: "Calmer l'anxiété",
    description: ``,
    duration: 27,
    pack: { name: "calmer_l_anxiete", file: "calmer-l-anxiete.mp3" },
  },
  {
    id: "53f195c2-a153-4d6a-8037-0ab456746643",
    rid: "pensees-negatives",
    title: "Pensées négatives",
    label: "Stopper ses pensées négatives",
    description: ``,
    duration: 36,
    pack: { name: "pensees_negatives", file: "pensees-negatives.mp3" },
  },
  {
    id: "6d9d729d-e52f-4f4b-81b8-6bf37ea88559",
    rid: "transformer-vos-peurs",
    title: "Transformer vos peurs",
    label: "Transformer vos peurs",
    description: ``,
    duration: 26,
    pack: { name: "transformer_vos_peurs", file: "transformer-vos-peurs.mp3" },
  },
  {
    id: "e122911f-4a24-49ff-9587-65129ef699a3",
    rid: "addictions",
    title: "Addictions",
    label: "Se libérer de ses addictions",
    description: ``,
    duration: 33,
    pack: { name: "addictions", file: "addictions.mp3" },
  },
  {
    id: "d46578d6-ef9b-431f-a3f2-04c8b36c4f07",
    rid: "gerer-le-stress",
    title: "Gérer le stress",
    label: "Gérer le stress",
    description: ``,
    duration: 22,
    pack: { name: "gerer_le_stress", file: "gerer-le-stress.mp3" },
  },
  {
    id: "a7b602ec-99ec-457c-92b2-32e855ed599d",
    rid: "gerer-la-douleur",
    title: "Gérer la douleur",
    label: "Gérer la douleur",
    description: ``,
    duration: 27,
    pack: { name: "gerer_la_douleur", file: "gerer-la-douleur.mp3" },
  },
  {
    id: "690db822-ff29-40b9-a3ee-85792d884498",
    rid: "reeducation-physique",
    title: "Rééductation physique",
    label: "Rééductation physique",
    description: ``,
    duration: 37,
    pack: { name: "reeducation_physique", file: "reeducation-physique.mp3" },
  },
  {
    id: "b8d87273-f9e8-447e-a1ba-031751424e2e",
    rid: "surmonter-sa-tristesse",
    title: "Surmonter sa tristesse",
    label: "Surmonter sa tristesse",
    description: ``,
    duration: 22,
    pack: { name: "surmonter_sa_tristesse", file: "surmonter-sa-tristesse.mp3" },
  },
  {
    id: "0b37df7c-5d5c-4a04-b983-1885e7ac4b0e",
    rid: "faire-son-deuil",
    title: "Faire son deuil",
    label: "Faire son deuil",
    description: ``,
    duration: 35,
    pack: { name: "faire_son_deuil", file: "faire-son-deuil.mp3" },
  },
  {
    id: "ec37a9f1-d164-4d89-bd6e-00e42eb0ac6d",
    rid: "soigner-son-passe",
    title: "Soigner son passé",
    label: "Soigner son passé",
    description: ``,
    duration: 23,
    pack: { name: "soigner_son_passe", file: "soigner-son-passe.mp3" },
  },
  {
    id: "9f94b828-7c4a-4603-94a5-0f6b2784b68d",
    rid: "intuition",
    title: "Intuition",
    label: "Développer son intuition",
    description: ``,
    duration: 32,
    pack: { name: "intuition", file: "intuition.mp3" },
  },
  {
    id: "009a1cf4-ba62-4907-8189-aabde6ea292a",
    rid: "prise-de-decision",
    title: "Prise de décision",
    label: "Prise de décision",
    description: ``,
    duration: 42,
    pack: { name: "prise-de-decision", file: "prise-de-decision.mp3" },
  },
  {
    id: "3a5c6d5b-bfa3-4cb2-9a40-20f63df2f6ae",
    rid: "immersion-sensorielle",
    title: "Immersion sensorielle",
    label: "Immersion sensorielle",
    description: ``,
    duration: 24,
    pack: { name: "immersion-sensorielle", file: "immersion-sensorielle.mp3" },
  },
  {
    id: "da4645ac-24ff-45bc-b66a-8420deae267d",
    rid: "nouveau-depart",
    title: "Nouveau départ",
    label: "Prendre un nouveau départ",
    description: ``,
    duration: 32,
    pack: { name: "nouveau_depart", file: "nouveau-depart.mp3" },
  },
  {
    id: "b60b55e4-f109-447c-89d4-e9c5085a1761",
    rid: "reussir-sa-vie",
    title: "Réussir sa vie",
    label: "Réussir sa vie",
    description: ``,
    duration: 36,
    pack: { name: "reussir_sa_vie", file: "reussir-sa-vie.mp3" },
  },
  {
    id: "fe20988e-7717-4797-a4f6-b0f5d1e0458a",
    rid: "magie-interieure",
    title: "Magie intérieure",
    label: "Activer votre magie intérieure",
    description: ``,
    duration: 41,
    pack: { name: "magie_interieure", file: "magie-interieure.mp3" },
  },
  {
    id: "5e0652e2-0895-4f4d-b2cb-03dd9fd06ff8",
    rid: "bain-d-hypnose",
    title: "Bain d'hypnose",
    label: "Bain d'hypnose",
    description: ``,
    duration: 40,
    pack: { name: "bain_d_hypnose", file: "bain-d-hypnose.mp3" },
  },
  {
    id: "20b9c903-bcd1-479e-9ee7-e3702fc8ef85",
    rid: "voyage-en-imagination",
    title: "Voyage en imagination",
    label: "Voyage en imagination",
    description: ``,
    duration: 35,
    pack: { name: "voyage_en_imagination", file: "voyage-en-imagination.mp3" },
  },
  {
    id: "72e43104-5b0f-4180-b091-27506aea4f64",
    rid: "auto-hypnose",
    title: "Auto hypnose",
    label: "Auto hypnose",
    description: ``,
    duration: 21,
    pack: { name: "auto_hypnose", file: "auto-hypnose.mp3" },
  },
  {
    id: "98b8ae9d-a123-47ca-8982-4f491242641e",
    rid: "l-inconscient",
    title: "L'inconscient",
    label: "Contacter son inconscient",
    description: ``,
    duration: 45,
    pack: { name: "l_inconscient", file: "l-inconscient.mp3" },
  },
  {
    id: "334b076c-0ff3-4bc4-a83e-9ed27091eee1",
    rid: "createur-de-realite",
    title: "Créateur de réalité",
    label: "Créateur de réalité",
    description: ``,
    duration: 47,
    pack: { name: "createur_de_realite", file: "createur-de-realite.mp3" },
  },
  {
    id: "db73e2f3-4d6b-4c0d-bde8-84614e33a59a",
    rid: "expansion",
    title: "Expansion",
    label: "Expansion de conscience",
    description: ``,
    duration: 24,
    pack: { name: "expansion", file: "expansion.mp3" },
  },
  {
    id: "9b4d2642-2d01-40c4-b7ba-b4411f65ecf0",
    rid: "histoire-de-la-vie",
    title: "Histoire de la vie",
    label: "Récit - Histoire de la vie",
    description: ``,
    duration: 46,
    pack: { name: "histoire_de_la_vie", file: "histoire-de-la-vie.mp3" },
  },
  {
    id: "b42aaf1c-7046-469c-ba8a-e8e99712d5ea",
    rid: "la-conscience",
    title: "La conscience",
    label: "Récit - La conscience",
    description: ``,
    duration: 40,
    pack: { name: "la_conscience", file: "la-conscience.mp3" },
  },
];
