import type { Sample } from "@/typings/recording";

export const SAMPLES: Sample[] = [
  {
    id: "efb3b76e-94d8-4a41-b3bf-7a39f81eea98",
    rid: "bien-dormir",
    title: "Bien dormir",
    label: "Bien dormir",
    description: `Comme son titre l'indique, cet enregistrement est destiné à vous accompagner durant votre endormissement, soit pour vous aider à vous endormir, soit pour faire en sorte que votre nuit se passe bien. Vous avez juste à poser les écouteurs ou le casque de votre smartphone sur vos oreilles, et laisser faire. Pas besoin d'écouter vraiment ou de chercher à comprendre, juste vous laisser bercer. L'accompagnement musical est minimal et, comme la voix, s'en ira progressivement afin de ne pas troubler votre sommeil.\n\nTexte composé par Patricia d'Angeli, puis enregistré également par elle (l'ambiance musicale est d'Olivier Lockert).`,
    duration: 19,
    pack: { name: "bien_dormir", file: "bien-dormir.mp3" },
  },
  {
    id: "69f1efb0-9dcd-41cb-8120-682d59b6b122",
    rid: "s-endormir",
    title: "S'endormir en auto-hypnose",
    label: "S'endormir en auto-hypnose",
    description: `Le premier protocole du livre "Auto-hypnose pour débutants" : comment trouver le sommeil. Ecoutez au casque, afin de profiter au mieux de l'accompagnement musical. Pour cette séance, une induction hypnotique a été utilisée parmi celles présentées dans le livre. Bien sûr, lorsque vous pratiquez de manière autonome, vous pouvez utiliser votre méthode préférée. De même, lorsque vous pratiquez en solo, vous n’avez pas besoin de parler ou de mentaliser les paroles. Il suffit de penser à ce que vous voulez, comme une intention. Avec la pratique, tout s’automatise et seule votre intention dirige la séance.`,
    duration: 30,
    pack: { name: "s_endormir", file: "s-endormir.mp3" },
  },
  {
    id: "2e93e241-e705-4047-9b03-c5bab2f4e2a4",
    rid: "dormir-bouclier-de-reve",
    title: "Bouclier de rêve",
    label: "Dormir : le bouclier de rêve",
    description: `Vous souffrez d'insomnie ? Autrement dit, vous n'avez pas seulement "du mal à vous endormir" : vous ne dormez pas du tout !\n\nLa première chose à faire est de consulter votre médecin afin de vérifier avec lui que votre insomnie n'a pas de cause physique (dérèglement hormonal, anémie, etc.). Si c'est le cas, votre médecin vous prescrira le traitement adapté.\n\nSi votre bilan est normal et que vous vous sentez stressé(e) ou anxieux(se), nous vous conseillons plutôt d'écouter les séances de notre chaîne dédiée à la gestion du stress et de l'anxiété.\n\nMais si tout semble à peu près équilibré dans votre vie, sans stress particulier ni tempérament anxieux, et que vous vous découvrez hypersensible - une sensibilité exacerbée par le manque de sommeil - à certaines idées, ruminations ou aux agressions du quotidien, au point que cela vous empêche véritablement de dormir (cela serait à l'origine de près de 40 % des insomnies, paraît-il) alors cette séance d'hypnose est faite pour vous !`,
    duration: 24,
    pack: { name: "dormir_bouclier_de_reve", file: "dormir-bouclier-de-reve.mp3" },
  },
  {
    id: "8fc48463-d7ff-4b03-a37a-bc90bb295af0",
    rid: "dormir-pays-imaginaire",
    title: "S'endormir au pays imaginaire",
    label: "S'endormir au pays imaginaire",
    description: `Le langage employé reste volontairement vague pour vous permettre de voyager dans votre "pays imaginaire", de explorer vos mondes intérieurs et le pays des rêves.\n\nSelon votre imagination, vous pourrez, à chaque écoute, découvrir de nouveaux paysages et vivre de nouvelles aventures en réécoutant cette même séance un autre soir.\n\nUne douce suggestion finale anticipe le geste que vous ferez, sans vous réveiller, pour éteindre la musique.\n\nBonne nuit !`,
    duration: 30,
    pack: { name: "dormir_pays_imaginaire", file: "dormir-pays-imaginaire.mp3" },
  },
  {
    id: "bbcbb0f2-9323-43bb-89b7-bc9e23a7d48f",
    rid: "dormir-enfant-interieur",
    title: "Dormir avec votre enfant intérieur",
    label: "Bien dormir avec votre enfant intérieur",
    description: `Patricia d'Angeli vous accompagne vers le sommeil pour une nuit ressourçante, au travers d'évocations poétiques centrées sur votre bien-être et la reconnexion avec votre enfant intérieur.`,
    duration: 24,
    pack: { name: "dormir_enfant_interieur", file: "dormir-enfant-interieur.mp3" },
  },
  {
    id: "897f00a4-5838-4963-b6c4-04ad849bfcb0",
    rid: "faire-le-plein-energie",
    title: "Faire le plein d'énergie",
    label: "Faire le plein d'énergie",
    description: `Cette séance vous apprendra à refaire "le plein d'énergie" de manière simple, en utilisant uniquement des moyens psychologiques.\n\nEn Hypnose Humaniste, cet exercice - dont Olivier Lockert vous présente ici la première variante - se pratique avant même l'induction hypnotique, et donc avant la partie proprement thérapeutique de l'intervention. Son but est de vous donner la force et l'élan nécessaires pour réussir votre séance de thérapie.\n\nCet enregistrement vous permettra d'abord de comprendre comment régénérer votre énergie naturellement et de façon autonome.\n\nPuis, Olivier Lockert vous guidera dans la pratique de cet exercice, que vous pourrez ensuite reproduire à volonté, dès que vous en sentirez le besoin, ou instaurer comme un rituel matinal.`,
    duration: 20,
    pack: { name: "faire_le_plein_energie", file: "faire-le-plein-energie.mp3" },
  },
  {
    id: "fba20c88-66f9-475a-96b4-43722c85fe0b",
    rid: "preventif",
    title: "Préventif",
    label: "Système immunitaire préventif",
    description: `Cette induction a été conçue, à l'origine, pour aider lors de l'épidémie de grippe H1N1 de l'hiver 2009. Cet enregistrement est à écouter avant l'enregistrement "Curatif" afin de bien comprendre l'esprit dans lequel vous mettre. Le texte est explicatif, avec de nombreuses métaphores. Le tout est dit assez rapidement, de manière à exciter, stimuler, vos processus psychophysiologiques.\n\nTexte et musique d'Olivier Lockert.`,
    duration: 27,
    pack: { name: "preventif", file: "preventif.mp3" },
  },
  {
    id: "27c5da5f-e3a8-4743-8627-cb8065dd80e7",
    rid: "curatif",
    title: "Curatif",
    label: "Système immunitaire curatif",
    description: `Cet accompagnement est curatif. C'est-à-dire que vous n'en avez besoin que si vous êtes malade. Le texte est dit lentement et la musique est hypnotique. Même si beaucoup de choses sont encore expliquées, le texte n'est pas pour votre esprit conscient, fermez les yeux et passez un bon moment, sans chercher à comprendre, ni même à écouter. S'il vous arrive de ne plus entendre, comme si vous pensiez à autre chose ou comme si vous aviez dormi : c'est parfait !`,
    duration: 36,
    pack: { name: "curatif", file: "curatif.mp3" },
  },
  {
    id: "a439d9f2-eac8-4ec6-8256-c2b003143869",
    rid: "renforcement",
    title: "Renforcement",
    label: "Renforcer son système immunitaire",
    description: `Voici un exercice sur le thème "Stimulez votre système immunitaire". Il s'agit ici de libérer un éventuel blocage émotionnel, dans les cas où tout semble correct au niveau du corps, et pourtant, vous n'allez pas mieux. Vous pouvez aussi écouter cette séance à titre préventif, avec l'idée suivante en tête : "Cher Inconscient, si quelque chose devait me stresser ou me bloquer, de là à fragiliser mon immunité, dis-le moi avant ou fais ce qu'il faut pour que tout se passe bien".\n\nTexte et voix d'Olivier Lockert.`,
    duration: 21,
    pack: { name: "renforcement", file: "renforcement.mp3" },
  },
  {
    id: "eddfd60e-b48f-47c0-bf01-ae40f4daa275",
    rid: "ressourcement",
    title: "Ressourcement",
    label: "Bulle de ressourcement thérapeutique",
    description: `L'idée est de se reconnecter aux forces vitales, puis de plonger dans un espace de ressourcement, afin de renforcer et d'accélérer la guérison du corps. Le fond sonore est lancinant, onirique, afin de vous bercer. Rien à faire, rien à penser, juste vous laisser faire. Allongez-vous ou installez-vous confortablement, et laissez aller. Dans les situations les plus difficiles, utilisez cette induction au moins une fois par jour. Vous pouvez vous endormir pendant l'accompagnement, car l'action consciente, volontaire, est inutile.`,
    duration: 30,
    pack: { name: "ressourcement", file: "ressourcement.mp3" },
  },
  {
    id: "dd0e3dee-3330-4383-b221-e829d2c20025",
    rid: "adaptation-aux-virus",
    title: "Adaptation aux virus",
    label: "Adaptation aux virus",
    description: `Une expérience d'auto-hypnose pour accélérer en vous l'adaptation à un nouveau virus. Que vous preniez cette idée comme une réalité concrète ou une métaphore, peu importe, si cela peut vous aider, à un niveau ou un autre. Il s'agit de soutien psychologique, qui peut venir en aide ou en complément de tout l'aspect sanitaire donc continuez bien à vous protéger, à prendre soin de vous. Vous pouvez renouveler cette expérience chaque jour, pendant quelques temps, si vous en avez l'envie ou si cela vous fait du bien.`,
    duration: 24,
    pack: { name: "adaptation_aux_virus", file: "adaptation-aux-virus.mp3" },
  },
  {
    id: "9bb5e6c5-e4b5-417d-93e3-f3f12dbfb333",
    rid: "retrouver-le-moral",
    title: "Retrouver le moral",
    label: "Retrouver le moral",
    description: `Après une introduction dynamique, cette séance vous montre comment agir par vous-même en auto-hypnose. L'accompagnement débute par une "ré-énergétisation" physique et psychologique. Ensuite, vous créerez un point d'ancrage pour retrouver forme et énergie à la demande (en dehors des séances). Pratiquez régulièrement pour maîtriser la technique. Souvenez-vous : un ancrage ne s'affaiblit que par le manque d'usage -
     plus vous l'utiliserez, plus il sera efficace !`,
    duration: 16,
    pack: { name: "retrouver_le_moral", file: "retrouver-le-moral.mp3" },
  },
  {
    id: "a0683c11-4dc5-414a-9643-9df6e9e9c5b0",
    rid: "joie-de-vivre",
    title: "Joie de vivre",
    label: "Retrouver sa joie de vivre",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous propose une séance d'hypnose où vous n'aurez qu'à vous laisser porter. Objectif : mobiliser votre esprit profond pour réveiller votre joie de vivre.\n\nCrédits audio : « Compass », « Tides » et « Pilgrim » de Some Where at Sea.`,
    duration: 23,
    pack: { name: "joie_de_vivre", file: "joie-de-vivre.mp3" },
  },
  {
    id: "d28062c7-0655-442c-8c54-0e3cff8b0350",
    rid: "confiance-en-soi",
    title: "Confiance en soi",
    label: "Confiance en soi",
    description: `Une séance structurée en explications, suggestions et métaphores pour restaurer la confiance en soi. Conçue pour une écoute unique - la première expérience peut suffire.\n\nProtocole conçu par Olivier Lockert, narré par Patricia d'Angeli.`,
    duration: 39,
    pack: { name: "confiance_en_soi", file: "confiance-en-soi.mp3" },
  },
  {
    id: "032e9cd5-d18d-4b7b-9961-4a54b610918a",
    rid: "estime-de-soi",
    title: "Estime de soi",
    label: "Estime de soi",
    description: `Voici un accompagnement très complémentaire à celui sur la Confiance en Soi. Le texte est de Patricia d'Angeli, qui souhaite vous faire découvrir ici le travail sur votre Critique intérieur, à l'origine de vos soucis d'estime de vous. Rien d'autre à faire que de vous laisser guider et suivre le protocole qui vous sera enseigné. Si cela va trop vite la première fois, pas de souci : laissez passer un jour ou deux, et réécoutez l'enregistrement. La seconde fois, vous y arriverez beaucoup mieux.`,
    duration: 25,
    pack: { name: "estime_de_soi", file: "estime-de-soi.mp3" },
  },
  {
    id: "872ee262-935b-4035-83d6-6bcb9cccd533",
    rid: "retrouver-sa-confiance",
    title: "Retrouver sa confiance",
    label: "Retrouver sa confiance en soi",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous propose une séance d'hypnose pour vous connecter au meilleur de vous-même et nettoyer ce qui vous empêche de vous sentir serein par rapport à vous-même.\n\nCrédits audio : « The Long Wait » de Dear Gravity, « Lucid Dreaming » de Dear Gravity, « December » de Dear Gravity, « Pacing » de Dear Gravity.`,
    duration: 29,
    pack: { name: "retrouver_sa_confiance", file: "retrouver-sa-confiance.mp3" },
  },
  {
    id: "4ce56de7-1723-47ab-b4b4-ea1cf60d3cc8",
    rid: "calmer-l-anxiete",
    title: "Calmer l'anxiété",
    label: "Calmer l'anxiété",
    description: `Cet enregistrement vous propose ici un accompagnement à sa manière : un voyage vers votre Enfant Intérieur, source des émotions qui assaillent les personnes souffrant d'anxiété, de crises d'angoisse, ou qui vivent des peurs sans fondement concret. Vous apprendrez à entrer en vous-même et à dialoguer avec certaines facettes de votre esprit inconscient. Ce travail intérieur pourra être repris régulièrement, jusqu'à ce que vous ayez l'automatisme de pensée qui vous permettra de ressentir ce dont a besoin votre esprit profond.\n\nTexte de Patricia d'AngeliLa et musique d'Olivier Lockert.`,
    duration: 27,
    pack: { name: "calmer_l_anxiete", file: "calmer-l-anxiete.mp3" },
  },
  {
    id: "53f195c2-a153-4d6a-8037-0ab456746643",
    rid: "pensees-negatives",
    title: "Pensées négatives",
    label: "Stopper ses pensées négatives",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous accompagne dans un voyage hypnotique intérieur, aux sources de vos pensées négatives : dévalorisation personnelle, auto-critique ou critique des autres, perfectionnisme exagéré, mauvaise estime de soi. La technique choisie est celle du "Soin du Critique", en Thérapie Symbolique Avancée (Patricia d'Angeli), apparentée à l'Hypnose Humaniste.\n\nCrédits audio : « Ember » de Michael-FK, « Lucid Dreaming » de Dear Gravity, « Pacing » de Dear Gravity, « The Veil » de Dear Gravity, « Longitude Travel » de Itai Argaman, « My Own Safe Haven » de Will van de Crommert.`,
    duration: 36,
    pack: { name: "pensees_negatives", file: "pensees-negatives.mp3" },
  },
  {
    id: "6d9d729d-e52f-4f4b-81b8-6bf37ea88559",
    rid: "transformer-vos-peurs",
    title: "Transformer vos peurs",
    label: "Transformer vos peurs",
    description: `Patricia d'Angeli vous conduit dans cette séance d'hypnose, en forme de quête intérieure, afin de vous aider à transformer vos peurs ou angoisses en une force créatrice. Cet accompagnement vous sera également utile en cas de maladie, en complément de votre suivi médical, afin d'activer en vous vos ressources profondes. Le travail symbolique a l'avantage de permettre un travail important sans avoir besoin de revivre quoi que ce soit de pénible.`,
    duration: 26,
    pack: { name: "transformer_vos_peurs", file: "transformer-vos-peurs.mp3" },
  },
  {
    id: "e122911f-4a24-49ff-9587-65129ef699a3",
    rid: "addictions",
    title: "Addictions",
    label: "Se libérer de ses addictions",
    description: `Il faudra simplement choisir en pensée le sujet sur lequel vous souhaitez travailler : faciliter l'arrêt du tabac, diminuer les boissons alcoolisées, les grignotages, les visites sur internet, les heures de jeu vidéo, l'argent perdu en loteries et jeux de hasard, etc. Comme expliqué dans le livre "Auto-hypnose pour Débutants", il y a de multiples causes possibles à une addiction - et certaines causes ne sont pas psychologiques du tout ! Les addictions graves peuvent nécessiter un suivi médical. L'Hypnose ne prend en charge que l'aspect psychologique. Un bon hypnothérapeute vous enverra éventuellement vérifier auprès d'un médecin si tout va bien "côté physique" (selon le type d'addiction).\n\nTexte et voix d'Olivier Lockert.`,
    duration: 33,
    pack: { name: "addictions", file: "addictions.mp3" },
  },
  {
    id: "d46578d6-ef9b-431f-a3f2-04c8b36c4f07",
    rid: "gerer-le-stress",
    title: "Gérer le stress",
    label: "Gérer le stress",
    description: `Vous serez guidé par la voix, durant ce que l'on appelle un cycle ultradien, qui correspond à l'activation d'une phase naturelle de régénération physique et psychologique. Cet enregistrement est à utiliser à la maison, en soutien pour les moments difficiles. Si vous avez un examen ou un rendez-vous important, une compétition sportive ou tout autre évènement stressant ponctuel, utilisez l'enregistrement suivant pour réactiver dans l'urgence les bienfaits de cette séance. Voix de Patricia D'Angeli`,
    duration: 22,
    pack: { name: "gerer_le_stress", file: "gerer-le-stress.mp3" },
  },
  {
    id: "a7b602ec-99ec-457c-92b2-32e855ed599d",
    rid: "gerer-la-douleur",
    title: "Gérer la douleur",
    label: "Gérer la douleur",
    description: `Notez que cette séance d'auto-hypnose ne remplace absolument pas le travail de votre médecin. Il s'agit de vous aider à rester zen pendant l'intervention et à gérer la douleur le mieux possible, en plus de ce que vous donnera le professionnel médical qui vous accompagnera. Il s'agit de soutien psychologique. Extrait des exercices du livre "Auto-hypnose pour Débutants" : la préparation à une intervention médicale.\n\nTexte et voix d'Olivier Lockert.`,
    duration: 27,
    pack: { name: "gerer_la_douleur", file: "gerer-la-douleur.mp3" },
  },
  {
    id: "690db822-ff29-40b9-a3ee-85792d884498",
    rid: "reeducation-physique",
    title: "Rééductation physique",
    label: "Rééductation physique",
    description: `Dernière variante du protocole d'apprentissage rapide, cette fois-ci pour aider ou soutenir une rééducation physique, que ce soit suite à une maladie ou à un accident : le fait de "faire les mouvements", d'abord mentalement, aide considérablement à mieux les réussir ensuite physiquement, avec votre kiné, rééducateur. Nous aurons donc une partie "visualisation" (pas obligé de "voir" pour ça, rassurez-vous) mais aussi une bonne partie d'activation de vos ressources profondes. Bien entendu, l'hypnose ne dispense pas d'un suivi médical, si vous en avez besoin. Mais elle vous permet d'obtenir de meilleurs résultats, plus vite, ce qui est motivant et vous aide à continuer avec le moral.\n\nTexte et voix d'Olivier Lockert.`,
    duration: 37,
    pack: { name: "reeducation_physique", file: "reeducation-physique.mp3" },
  },
  {
    id: "b8d87273-f9e8-447e-a1ba-031751424e2e",
    rid: "surmonter-sa-tristesse",
    title: "Surmonter sa tristesse",
    label: "Surmonter sa tristesse",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous accompagne dans une véritable transformation intérieure, à la source indéfinie de la tristesse que vous ressentez, afin de la métamorphoser et remettre ainsi la lumière au cœur de votre vie.\n\nCrédits audio : « Cold in your bones » de Kyle Preston, « Exploration » de Kyle Preston, « Dark tension » de Kyle Preston, « Foreboding » de Kyle Preston, « Dont wake me up » de Josh Leake.`,
    duration: 22,
    pack: { name: "surmonter_sa_tristesse", file: "surmonter-sa-tristesse.mp3" },
  },
  {
    id: "0b37df7c-5d5c-4a04-b983-1885e7ac4b0e",
    rid: "faire-son-deuil",
    title: "Faire son deuil",
    label: "Faire son deuil",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous aide aujourd'hui à surmonter la perte d'un proche (décès, divorce, rupture amicale), quand vous avez de la difficulté à faire votre deuil par vous-même.\n\nCrédits audio : « Cast Riddance » de Dear Gravity, « Cold » de Borrtex, « Eternity » de Borrtex, « Rising Storm » de CK Martin, « Impavid » de Charlie Ryan, « Seven Years » de Josh Leake.`,
    duration: 35,
    pack: { name: "faire_son_deuil", file: "faire-son-deuil.mp3" },
  },
  {
    id: "ec37a9f1-d164-4d89-bd6e-00e42eb0ac6d",
    rid: "soigner-son-passe",
    title: "Soigner son passé",
    label: "Soigner son passé",
    description: `Souvent, nos soucis viennent d'un passé douloureux, que l'on peut travailler en thérapie personnelle. Ce travail peut être long et difficile. Surtout, il confronte à nouveau avec des expériences que l'on préfèrerait oublier. Cet accompagnement, sur vos Chemins de Lumière, est une régression symbolique vers vos racines transgénérationnelles (parents, grand-parents, etc). Le côté symbolique a l'avantage de permettre un travail sur le passé sans avoir besoin de revivre des souvenirs douloureux. De plus, par nature, les symboles incluent davantage d'éléments que des souvenirs concrets - sans que l'on sache.`,
    duration: 23,
    pack: { name: "soigner_son_passe", file: "soigner-son-passe.mp3" },
  },
  {
    id: "9f94b828-7c4a-4603-94a5-0f6b2784b68d",
    rid: "intuition",
    title: "Intuition",
    label: "Développer son intuition",
    description: `Le domaine de l'intuition est bien plus vaste qu'il n'y paraît à première vue. Les personnes en meilleure santé vivent et se nourrissent intuitivement mieux que les autres. Elles ne le font pas exprès. Prenons l'exemple d'une personne à qui tout réussit, qui a de la chance : elle semble savoir à chaque fois quoi faire, et pourtant ce n'est ni conscient, ni volontaire... C'est cela, l'intuition : le ressenti profond qui guide vos pas, souvent même sans que vous ne le sachiez. C'est ce qu'il y a de plus important pour vivre bien et en bonne santé, pour réussir sa vie et suivre le chemin qui a du cœur.\n\nTexte co-écrit par Patricia d'Angeli et Olivier Lockert. Le fond musical est d'Olivier Lockert.`,
    duration: 32,
    pack: { name: "intuition", file: "intuition.mp3" },
  },
  {
    id: "009a1cf4-ba62-4907-8189-aabde6ea292a",
    rid: "prise-de-decision",
    title: "Prise de décision",
    label: "Prise de décision",
    description: `Cette séance peut vous aider pour les situations de conflit, les dilemmes, ainsi que pour renforcer votre conviction et votre stabilité intérieure, en cas de prise de position décisive pour le futur. La technique choisie ("Reconstruction Hypnotique", en Nouvelle Hypnose) permet de stimuler la synthèse de votre Inconscient. Elle passe par une métaphore polymorphique, afin de s'adapter au plus grand nombre. \n\nTexte et voix d'Olivier Lockert.\n\nCrédits audio : « Solitude » de Michelle Nobler, « The Rain » de Sid Acharya, « The Sky » de Sid Acharya, « Things We Wouldn't Say » de Mickael FK, « Faith » de Mickael FK, « Incandescent With Passion » de CK Martin.`,
    duration: 42,
    pack: { name: "prise_de_decision", file: "prise-de-decision.mp3" },
  },
  {
    id: "3a5c6d5b-bfa3-4cb2-9a40-20f63df2f6ae",
    rid: "immersion-sensorielle",
    title: "Immersion sensorielle",
    label: "Immersion sensorielle",
    description: `Cette séance vient en conclusion de la préparation progressive à l'auto-hypnose. C'est l'étape juste avant de passer aux inductions hypnotiques. Cette séance est un exemple d'application. En apprenant l'auto-hypnose, vous utiliserez vos propres pensées, vos phrases personnelles, différentes des miennes. Ce sera à la fois plus simple pour vous et plus adapté, car tout viendra de vous.\n\nTexte d'Olivier Lockert.`,
    duration: 24,
    pack: { name: "immersion_sensorielle", file: "immersion-sensorielle.mp3" },
  },
  {
    id: "da4645ac-24ff-45bc-b66a-8420deae267d",
    rid: "nouveau-depart",
    title: "Nouveau départ",
    label: "Prendre un nouveau départ",
    description: `Alexandre Lockert, psychologue, psychothérapeute et hypnothérapeute (IFHE, Paris) vous aide à vous libérer des restes du passé et à épurer votre environnement pour mieux vous propulser dans un avenir meilleur. La technique choisie est celle de l'Eclosion, en Hypnose Humaniste.\n\nLa musique crescendo au final apaisée est de Pascal Lengagne.`,
    duration: 32,
    pack: { name: "nouveau_depart", file: "nouveau-depart.mp3" },
  },
  {
    id: "b60b55e4-f109-447c-89d4-e9c5085a1761",
    rid: "reussir-sa-vie",
    title: "Réussir sa vie",
    label: "Réussir sa vie",
    description: `Cet accompagnement en Hypnose Humaniste vous propose de travailler sur ce qui bloque éventuellement en vous, afin que vous soyez pleinement ouvert au monde et connecté à vous-même, intuitif et capable de marcher chaque jour sur votre meilleur chemin de vie.\n\nTexte et musique d'Olivier Lockert.`,
    duration: 36,
    pack: { name: "reussir_sa_vie", file: "reussir-sa-vie.mp3" },
  },
  {
    id: "fe20988e-7717-4797-a4f6-b0f5d1e0458a",
    rid: "magie-interieure",
    title: "Magie intérieure",
    label: "Activer votre magie intérieure",
    description: `Cet accompagnement d'Olivier Lockert vous aidera à activer vos ressources profondes et inconscientes. Vous pourrez demander l'aide de votre esprit profond pour résoudre des problèmes pour lesquels vous n'avez pas de solution, ou pour améliorer votre quotidien, même si tout va déjà très bien.\n\nTexte et musique d'Olivier Lockert.`,
    duration: 41,
    pack: { name: "magie_interieure", file: "magie-interieure.mp3" },
  },
  {
    id: "5e0652e2-0895-4f4d-b2cb-03dd9fd06ff8",
    rid: "bain-d-hypnose",
    title: "Bain d'hypnose",
    label: "Bain d'hypnose",
    description: `Cet enregistrement vous permet de vous ressourcer, en vous laissant simplement "baigner dans l'hypnose", comme on le faisait il y a des millénaires dans les fameux Temples d'Aesclapios, à l'époque antique. Vous pouvez utiliser cette séance dans les moments de stress, pour retrouver votre énergie, dans les périodes de fatigue ou pour une convalescence. Ecoutez la séance de préférence avec un casque audio, afin de profiter au mieux de l'accompagnement musical.\n\nLe texte est d'Olivier Lockert et la musique a été composée par Pascal Lengagne.`,
    duration: 40,
    pack: { name: "bain_d_hypnose", file: "bain-d-hypnose.mp3" },
  },
  {
    id: "20b9c903-bcd1-479e-9ee7-e3702fc8ef85",
    rid: "voyage-en-imagination",
    title: "Voyage en imagination",
    label: "Voyage en imagination",
    description: `Besoin de prendre l'air, de vous aérer ou de changer un peu d'horizon ? Voici ce qui va vous aider à retrouver un peu d'énergie et de bonne humeur. Cette séance n'est pas à proprement parler "thérapeutique", elle n'inclut ni techniques de langage, ni protocole thérapeutique. C'est une métaphore, structurée sur plusieurs niveaux de symboles, que vous reconnaitrez facilement. Vous n'avez rien à faire d'autre que profiter du moment, vous laisser porter, que vous restiez conscient ou non. Bon voyage !\n\nCrédits audio : « Regenerate-iii » de E-J-R-M, « Dream » de Tom Goldstein, « Daydreamer » de Tom Goldstein, « Patrick Day » de Tom Goldstein, « Morning Sunshine » de Tom Goldstein, « Hills & Valley » de Marshall Usinger, « She » de Josh Lake.`,
    duration: 35,
    pack: { name: "voyage_en_imagination", file: "voyage-en-imagination.mp3" },
  },
  {
    id: "72e43104-5b0f-4180-b091-27506aea4f64",
    rid: "auto-hypnose",
    title: "Auto hypnose",
    label: "Auto hypnose",
    description: `Cet enregistrement peut vous aider avant une thérapie ou avant une formation en hypnose ou auto-hypnose. Le texte est en "tu", car c'est ainsi que vous aurez à vous parler ensuite, lorsque vous pratiquerez tout seul. En fait, pas besoin de parler vraiment, ni même de penser exactement à ces phrases, il suffit d'avoir l'intention que les choses se fassent - et cela fonctionnera tout seul. Se tutoyer soi-même (ou parler à l'Inconscient) permet la dissociation, à la base de l'état d'hypnose.`,
    duration: 21,
    pack: { name: "auto_hypnose", file: "auto-hypnose.mp3" },
  },
  {
    id: "98b8ae9d-a123-47ca-8982-4f491242641e",
    rid: "l-inconscient",
    title: "L'inconscient",
    label: "Contacter son inconscient",
    description: `Voici les bases, en hypnose, pour contacter et converser avec votre Inconscient : vous apprendrez à établir un signaling, d'abord sans signification particulière, puis en stipulant les signes oui et non, ce qui vous permettra d'obtenir des réponses directes de votre Inconscient. Dans la seconde partie de l'accompagnement, vous apprendrez à interagir symboliquement avec votre Inconscient.`,
    duration: 45,
    pack: { name: "l_inconscient", file: "l-inconscient.mp3" },
  },
  {
    id: "334b076c-0ff3-4bc4-a83e-9ed27091eee1",
    rid: "createur-de-realite",
    title: "Créateur de réalité",
    label: "Créateur de réalité",
    description: `Vous souhaitez en savoir plus sur l'art de créer votre réalité ? Quoi que vous ayez, quoi que vous recherchiez, il est facile de comprendre qu'en devenant "créateur" de votre vie, vous pourrez trouver une solution. Si vous avez su générer les problèmes de votre vie, en apprenant à créer votre réalité, vous vous fabriquerez une existence meilleure. Créer sa réalité est la base de toutes choses. La technique, aussi puissante soit-elle, ne fonctionne que grâce à vous. C'est en vous forgeant vous-même que vous réussirez à faire naître la vie de vos rêves. C'est probablement la chose la plus difficile, travailler sur soi, mais c'est aussi la plus belle de toute l'existence.`,
    duration: 47,
    pack: { name: "createur_de_realite", file: "createur-de-realite.mp3" },
  },
  {
    id: "db73e2f3-4d6b-4c0d-bde8-84614e33a59a",
    rid: "expansion",
    title: "Expansion",
    label: "Expansion de conscience",
    description: `Cet enregistrement est un exemple d'induction hypnotique d'Hypnose Humaniste. L'induction est suivie d'un exemple d'intervention thérapeutique symbolique simple. Il est conçu pour plaire aux personnes plutôt "cerveau droit" (intuitives, fantaisistes, créatives). Il est possible que vous entriez dans une transe normale, dissociée conscient/inconscient. Pour éviter cela, il faut réellement vous accrocher ici et maintenant, quitte à ne pas entrer en transe au début. Il est plus facile de se laisser emporter par l'Inconscient que de gagner en conscience !`,
    duration: 24,
    pack: { name: "expansion", file: "expansion.mp3" },
  },
  {
    id: "9b4d2642-2d01-40c4-b7ba-b4411f65ecf0",
    rid: "histoire-de-la-vie",
    title: "Histoire de la vie",
    label: "Récit - Histoire de la vie",
    description: `Olivier Lockert vous présente la structure existentielle, la vaste vision de la Vie de l'Hypnose Humaniste. Cette présentation a pris les formes d'une histoire, comme un conte, afin de conserver la liberté de penser en termes philosophiques et psychologiques, plutôt que seulement appuyé sur des bases concrètes et vérifiables. Si vous recherchez seulement l'aspect thérapeutique de l'Hypnose Humaniste, vous ne serez probablement pas intéressé par ce récit.\n\nTexte d'Olivier Lockert et voix de Patricia d'Angeli.`,
    duration: 46,
    pack: { name: "histoire_de_la_vie", file: "histoire-de-la-vie.mp3" },
  },
  {
    id: "b42aaf1c-7046-469c-ba8a-e8e99712d5ea",
    rid: "la-conscience",
    title: "La conscience",
    label: "Récit - La conscience",
    description: `Olivier Lockert vous présente la version audio de son article sur "La Conscience: elle existe et ça se voit !". Si vous recherchez seulement l'aspect thérapeutique de l'Hypnose Humaniste, vous ne serez probablement pas intéressé par ce récit.\n\nTexte et voix d'Olivier Lockert.`,
    duration: 40,
    pack: { name: "la_conscience", file: "la-conscience.mp3" },
  },
];
