/* eslint-disable @typescript-eslint/no-require-imports */
import type { ImageSourcePropType } from "react-native";

import type { Sample } from "@/typings/recording";

export const SAMPLE_THUMBNAILS: Record<Sample["rid"], ImageSourcePropType> = {
  "bien-dormir": require("@/assets/thumbnails/bien-dormir.jpeg"),
  "s-endormir": require("@/assets/thumbnails/s-endormir.jpeg"),
  "dormir-bouclier-de-reve": require("@/assets/thumbnails/dormir-bouclier-de-reve.jpeg"),
  "dormir-pays-imaginaire": require("@/assets/thumbnails/dormir-pays-imaginaire.jpeg"),
  "dormir-enfant-interieur": require("@/assets/thumbnails/dormir-enfant-interieur.jpeg"),
  "faire-le-plein-energie": require("@/assets/thumbnails/faire-le-plein-energie.jpeg"),
  preventif: require("@/assets/thumbnails/preventif.jpeg"),
  curatif: require("@/assets/thumbnails/curatif.jpeg"),
  renforcement: require("@/assets/thumbnails/renforcement.jpeg"),
  ressourcement: require("@/assets/thumbnails/ressourcement.jpeg"),
  "adaptation-aux-virus": require("@/assets/thumbnails/adaptation-aux-virus.jpeg"),
  "retrouver-le-moral": require("@/assets/thumbnails/retrouver-le-moral.jpeg"),
  "joie-de-vivre": require("@/assets/thumbnails/joie-de-vivre.jpeg"),
  "confiance-en-soi": require("@/assets/thumbnails/confiance-en-soi.jpeg"),
  "estime-de-soi": require("@/assets/thumbnails/estime-de-soi.jpeg"),
  "retrouver-sa-confiance": require("@/assets/thumbnails/retrouver-sa-confiance.jpeg"),
  "calmer-l-anxiete": require("@/assets/thumbnails/calmer-l-anxiete.jpeg"),
  "pensees-negatives": require("@/assets/thumbnails/pensees-negatives.jpeg"),
  "transformer-vos-peurs": require("@/assets/thumbnails/transformer-vos-peurs.jpeg"),
  addictions: require("@/assets/thumbnails/addictions.jpeg"),
  "gerer-le-stress": require("@/assets/thumbnails/gerer-le-stress.jpeg"),
  "gerer-la-douleur": require("@/assets/thumbnails/gerer-la-douleur.jpeg"),
  "reeducation-physique": require("@/assets/thumbnails/reeducation-physique.jpeg"),
  "surmonter-sa-tristesse": require("@/assets/thumbnails/surmonter-sa-tristesse.jpeg"),
  "faire-son-deuil": require("@/assets/thumbnails/faire-son-deuil.jpeg"),
  "soigner-son-passe": require("@/assets/thumbnails/soigner-son-passe.jpeg"),
  intuition: require("@/assets/thumbnails/intuition.jpeg"),
  "prise-de-decision": require("@/assets/thumbnails/prise-de-decision.jpeg"),
  "immersion-sensorielle": require("@/assets/thumbnails/immersion-sensorielle.jpeg"),
  "nouveau-depart": require("@/assets/thumbnails/nouveau-depart.jpeg"),
  "reussir-sa-vie": require("@/assets/thumbnails/reussir-sa-vie.jpeg"),
  "magie-interieure": require("@/assets/thumbnails/magie-interieure.jpeg"),
  "bain-d-hypnose": require("@/assets/thumbnails/bain-d-hypnose.jpeg"),
  "voyage-en-imagination": require("@/assets/thumbnails/voyage-en-imagination.jpeg"),
  "auto-hypnose": require("@/assets/thumbnails/auto-hypnose.jpeg"),
  "l-inconscient": require("@/assets/thumbnails/l-inconscient.jpeg"),
  "createur-de-realite": require("@/assets/thumbnails/createur-de-realite.jpeg"),
  expansion: require("@/assets/thumbnails/expansion.jpeg"),
  "histoire-de-la-vie": require("@/assets/thumbnails/histoire-de-la-vie.jpeg"),
  "la-conscience": require("@/assets/thumbnails/la-conscience.jpeg"),

  // testing
  "sample-rid": require("@/assets/testing/thumbnail.jpeg"),
};
