export interface PlayerState {
  isPlaying: boolean;
  position: number;
  duration: number;
}

export interface onPlayerStatusUpdateEvent {
  status: PlayerStatus;
}

export interface OnPlayerErrorEvent {
  error: PlayerError;
}

export enum PlayerStatus {
  STATE_IDLE = 1,
  STATE_BUFFERING = 2,
  STATE_READY = 3,
  STATE_ENDED = 4,
}

export enum PlayerError {
  ERROR_CODE_INVALID_STATE = -2,
  ERROR_CODE_BAD_VALUE = -3,
  ERROR_CODE_PERMISSION_DENIED = -4,
  ERROR_CODE_NOT_SUPPORTED = -6,
  ERROR_CODE_DISCONNECTED = -100,
  ERROR_CODE_AUTHENTICATION_EXPIRED = -102,
  ERROR_CODE_PREMIUM_ACCOUNT_REQUIRED = -103,
  ERROR_CODE_CONCURRENT_STREAM_LIMIT = -104,
  ERROR_CODE_PARENTAL_CONTROL_RESTRICTED = -105,
  ERROR_CODE_NOT_AVAILABLE_IN_REGION = -106,
  ERROR_CODE_SKIP_LIMIT_REACHED = -107,
  ERROR_CODE_SETUP_REQUIRED = -108,
  ERROR_CODE_END_OF_PLAYLIST = -109,
  ERROR_CODE_CONTENT_ALREADY_PLAYING = -110,

  ERROR_CODE_UNSPECIFIED = 1000,
  ERROR_CODE_REMOTE_ERROR = 1001,
  ERROR_CODE_BEHIND_LIVE_WINDOW = 1002,
  ERROR_CODE_TIMEOUT = 1003,
  ERROR_CODE_FAILED_RUNTIME_CHECK = 1004,

  ERROR_CODE_IO_UNSPECIFIED = 2000,
  ERROR_CODE_IO_NETWORK_CONNECTION_FAILED = 2001,
  ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT = 2002,
  ERROR_CODE_IO_INVALID_HTTP_CONTENT_TYPE = 2003,
  ERROR_CODE_IO_BAD_HTTP_STATUS = 2004,
  ERROR_CODE_IO_FILE_NOT_FOUND = 2005,
  ERROR_CODE_IO_NO_PERMISSION = 2006,
  ERROR_CODE_IO_CLEARTEXT_NOT_PERMITTED = 2007,
  ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE = 2008,

  ERROR_CODE_PARSING_CONTAINER_MALFORMED = 3001,
  ERROR_CODE_PARSING_MANIFEST_MALFORMED = 3002,
  ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED = 3003,
  ERROR_CODE_PARSING_MANIFEST_UNSUPPORTED = 3004,

  ERROR_CODE_DECODER_INIT_FAILED = 4001,
  ERROR_CODE_DECODER_QUERY_FAILED = 4002,
  ERROR_CODE_DECODING_FAILED = 4003,
  ERROR_CODE_DECODING_FORMAT_EXCEEDS_CAPABILITIES = 4004,
  ERROR_CODE_DECODING_FORMAT_UNSUPPORTED = 4005,
  ERROR_CODE_DECODING_RESOURCES_RECLAIMED = 4006,

  ERROR_CODE_AUDIO_TRACK_INIT_FAILED = 5001,
  ERROR_CODE_AUDIO_TRACK_WRITE_FAILED = 5002,
  ERROR_CODE_AUDIO_TRACK_OFFLOAD_WRITE_FAILED = 5003,
  ERROR_CODE_AUDIO_TRACK_OFFLOAD_INIT_FAILED = 5004,

  ERROR_CODE_DRM_UNSPECIFIED = 6000,
  ERROR_CODE_DRM_SCHEME_UNSUPPORTED = 6001,
  ERROR_CODE_DRM_PROVISIONING_FAILED = 6002,
  ERROR_CODE_DRM_CONTENT_ERROR = 6003,
  ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED = 6004,
  ERROR_CODE_DRM_DISALLOWED_OPERATION = 6005,
  ERROR_CODE_DRM_SYSTEM_ERROR = 6006,
  ERROR_CODE_DRM_DEVICE_REVOKED = 6007,
  ERROR_CODE_DRM_LICENSE_EXPIRED = 6008,
}
